### ISSUE TITLE
How to increase the maximum message size that is sent from the browser

### ISSUE THREAD

**Issue by diconart** [tailhook/zerogw#38]
When sending a large message from a browser, the web socket server disconnects, what needs to be written in the config to fix this?

**Comment by diconart** [comment]
"/api*":
              websocket:
                enabled: yes  
topic-hash-size: 100ki  // Not working

**Comment by tailhook** [comment]
I can't see any particular limit in websocket message codec. So it's either some bug or memory error, or some limit on specific message kind.

**Comment by diconart** [comment]
If there was not enough memory, would the web socket server fall?

**Comment by diconart** [comment]
Config.yaml

``
Server:
  zmq-io-threads: 4
  disk-io-threads: 4
  listen:
    - host: 0.0.0.0
      port: 8001
  error-log:
    level: 7
    warning-timeout: 300
  mime-types:
    extra:
      yaml: text/x-yaml
      mov: application/x-movable
    no-warnings: yes
Routing:
  routing: !Suffix ~
  routing-by: !Header Host
  map:    
      "*:8001":
        routing: !Prefix ~
        routing-by: !Uri ~
        map:  
            "/api*":
              websocket:
                enabled: yes             
                forward: !zmq.Push
                - !zmq.Bind "tcp://0.0.0.0:8002"
                subscribe: !zmq.Sub
                - !zmq.Bind "tcp://0.0.0.0:8003"   

``

**Comment by diconart** [comment]
Screenshot https://i.imgur.com/G6887Vz.jpg

**Comment by diconart** [comment]
The problem is in the volume of data sent, as soon as I remove one symbol, it is sent, as I add one connection break

**Comment by diconart** [comment]
Successful if send message with size max 16,0 Kb (16 384 byte)

**Comment by tailhook** [comment]
Maybe it's here: https://github.com/tailhook/libwebsite/blob/master/src/core.c#L1119

**Comment by diconart** [comment]
Thanks It works
